### ISSUE TITLE
Exception during `git bigstore pull`

### ISSUE THREAD

**Issue by jansel** [lionheart/git-bigstore#34]
```
...
  File "/usr/local/lib/python2.7/dist-packages/bigstore/bigstore.py", line 282, in pull
    g().notes("--ref=bigstore", "add", "-m", "bigstore")
  File "/usr/local/lib/python2.7/dist-packages/git/cmd.py", line 450, in <lambda>
    return lambda *args, **kwargs: self._call_process(name, *args, **kwargs)
  File "/usr/local/lib/python2.7/dist-packages/git/cmd.py", line 902, in _call_process
    return self.execute(make_call(), **_kwargs)
  File "/usr/local/lib/python2.7/dist-packages/git/cmd.py", line 695, in execute
    raise GitCommandError(command, status, stderr_value)
git.exc.GitCommandError: 'git notes --ref=bigstore add -m bigstore' returned with exit code 1
stderr: 'error: Cannot add notes. Found existing notes for object fc559df2dbc6a822d30b4a4ab498e3681ffe0155. Use '-f' to overwrite existing notes'
```

**Comment by michaelweinstein** [comment]
Did you ever figure this out? 
I'm getting the same error. When I try removing notes for named object, git tells me no note exists (and there shouldn't be any yet).

**Comment by jansel** [comment]
I believe this was fixed in #36 (it removes the offending line and merges it with an equivalent line that catches the exception).

Are you running the latest version?  If so, post your stack trace.

**Comment by michaelweinstein** [comment]
Thanks so much. I'm not exactly sure how to check the version explicitly, I couldn't find info on the wiki? 
I installed bigstore through `pip` yesterday so I'm not sure if the latest version is updated there. I can post the stack trace if so though.

**Comment by dlo** [comment]
I'm checking right now, let me see what's currently up there and if @jansel's fix made it in.

**Comment by michaelweinstein** [comment]
Thanks so much for your help. Pip may not install or upgrade to the latest bigstore version, `metadata.py` seems to indicate 1.0.0

**Comment by dlo** [comment]
Looks like PyPi changed their package updating API. Hold tight while I tighten the screws…

**Comment by dlo** [comment]
Done!

**Comment by michaelweinstein** [comment]
Thanks so much, you're a life saver!
